language: python

python:
  - "2.7"

# command to install dependencies, e.g. 
install: pip install -r requirements.txt --use-mirrors

# # command to run tests, e.g. python setup.py test
script:
  - make tests
  - make coverage

# Report to coveralls
after_success:
   - coveralls
